spring.application.name:
  J2EE
#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j2ee
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    port: 587
    username: 1870476411@qq.com
    password: mhsjyxjtsqtugibh
    default-encoding: utf-8
    properties:
      mail:
        from: 1870476411@qq.com
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          debug: true
  #redis
  data:
    redis:
      port: 6379

# 驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# swagger-springdoc-openapi项目配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.pixxiu.j2ee
knife4j:
  enable: true
  setting:
    language: zh_cn


